### ISSUE TITLE
Install and compile schemas with i18n

### ISSUE THREAD

**Issue by jgildred** [elementary/docs#100]
When the developer gets to section https://docs.elementary.io/develop/apis/state-saving#install-and-compile-schemas-with-meson, there is a description of how to install gschema.xml, but no mention of how to localize it.

Simply applying the method described in the previous Translations section (using i18n.merge_file() in meson.build) does not appear to work as it results in an error "cannot locate ITS rules" for the gschema file.

May be useful to point out where new translation steps are required.

**Comment by danrabbit** [comment]
gsettings schemas are used for your app to store its own data and are not user facing. The only time these strings would ever been shown is in developer tools. They're not expected to be localized

**Comment by jgildred** [comment]
Makes sense. Thanks. Not sure if it's worth saying that in the docs, but could be helpful to clarify.
