### ISSUE TITLE
Dark Style Support

### ISSUE THREAD

**Issue by Suzie97** [elementary/docs#111]
Right now docs is always light, even if the system is set to dark style. This gets disturbing as when I frequently read the docs for reference. But my terminal, code editor and the environment is dark. So it hurts my eyes.

**Comment by danrabbit** [comment]
We use [GitBook](https://github.com/gitbookio) for our docs, so this would need to be reported there since we don't have that kind of theming control

Closing as "Out of scope" since this can't be solved in the scope of this repo
