### ISSUE TITLE
Publishing requirements link goes to old instructions

### ISSUE THREAD

**Issue by aral** [elementary/docs#149]
### What Happened?

On https://docs.elementary.io/develop/appcenter/submission-process, the “publishing requirements” links goes to https://github.com/elementary/houston/wiki/Before-You-Publish which appears to contain pre-Flatpak/pre-Odin instructions.

### Steps to Reproduce

Go to https://docs.elementary.io/develop/appcenter/submission-process and click on “publishing requirements”.

### Expected Behavior

It should take you to the latest instructions.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

n/a

**Comment by ryonakano** [comment]
This looks like fixed in latest doc :)
