### ISSUE TITLE
`app-id` recommendation conflict with Flathub documentation

### ISSUE THREAD

**Issue by lukors** [elementary/docs#158]
The official Flatpak docs have the following in its list of "examples of bad IDs" on [this page](https://docs.flatpak.org/en/latest/conventions.html):

> - `com.github.foo.Bar`
>  
>   While a project may be hosted on GitHub it does not have any control over the `github.com` domain. Instead you should use `io.github` as shown above.

The [elementary packaging documentation](https://docs.elementary.io/develop/writing-apps/our-first-app/packaging) gives the following instructions:

> Create a `com.github.yourusername.yourrepositoryname.yml` file in your project root with the following contents:

The elementary documentation recommends a practice which the Flatpak documentation explicitly lists as bad practice.

### Suggested solutions
1. Make it recommend `io.github` instead of `com.github`.
2. Add a section explaining why using `com.github` isn't actually bad practice like it says in the Flatpak documentation.

**Comment by ryonakano** [comment]
Yes, we should recommend developers to use the `io.github` domain instead. Flathub disallows newly-submitted apps using `com.github` domain (causes linter error) so it's painful for developers to re-namespace their app if they develop it following our documentation and then submit it to both AppCenter and Flathub.
