### ISSUE TITLE
add kotava language

### ISSUE THREAD

**Issue by telmobss1** [elementary/docs#160]
### Problem

Add the kotava language for speakers of kotava

### Proposal

Translation on the weblate

### Prior Art (Optional)

Adding the kotava option to the weblate so that I and the rest of the community can translate

**Comment by danrabbit** [comment]
Our developer documentation is typically not translated since developers need to know English to write Vala and use platform libraries anyways

If this issue was meant for some other kind of documentation, please let me know and I can move it to the correct issue tracker :)

**Comment by telmobss1** [comment]
translate the interface and applications to Kotava, that's basically it
