### ISSUE TITLE
Settings Urls

### ISSUE THREAD

**Issue by danirabbit** [elementary/docs#190]
### Problem

We have a great system for launching system settings to specific settings panes that's helpful for apps to point you to things like permission settings, but it's not documented

### Proposal

Document the settings URLs. Maybe even make Granite constants so we can keep them up to date and deprecate etc that way?

**Comment by Antolius** [comment]
Would something [like this](https://github.com/elementary/granite/pull/649/files#diff-692820178d7210fa46b7f029d019987b1bb71cd5e6339d1720a2a85116972357R186-R189) work?

Once we agree on the constant naming convention I can add remaining URLs to granite. Then I can add a simple docs page (perhaps under the APIS section) which would illustrate their usage with a concrete use-case. And lastly I could update individual switchboard plugins to actually use those constants too (if that makes sense).
