### ISSUE TITLE
Recommend JSON for flatpak manifest instead of YML

### ISSUE THREAD

**Issue by danirabbit** [elementary/docs#209]
### Problem

YML feels easier for the simplest case but for more complex cases tools like External Data Checker require using JSON. It's a pain to tell a developer to use YML for their manifest until their app wants to add a new feature with a dependency outside our platform and now they have to convert their manifest to JSON for the best experience

### Proposal

We should just recommend JSON from the beginning

**Comment by ryonakano** [comment]
> for more complex cases tools like External Data Checker require using JSON

FYI External Data Checker works for YML too: https://github.com/ryonakano/atlas/pull/79

**Comment by danirabbit** [comment]
Oh!! Is that new? For some reason I thought it didn't work for yaml manifests 🤔

**Comment by ryonakano** [comment]
I began to use External Data Checker recently so I'm not sure if it didn't work for YML before, but it does work now at least in my (not complex) usage :sunglasses:

**Comment by danirabbit** [comment]
Gonna go ahead and close this then :)
