### ISSUE TITLE
Add Flatpak Docs

### ISSUE THREAD

**Issue by danyeaw** [elementary/docs#41]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
The current docs say that debian packages are a hard requirement. I understand that the AppCenter now allows for Flatpak apps, but it doesn't mention this in the documentation.

**Describe the solution you'd like**
Add Flatpak to the documentation if it is supported.

**Comment by danrabbit** [comment]
Flatpak isn't yet supported in AppCenter Dashboard, but it is planned

**Comment by danyeaw** [comment]
@danrabbit Thanks, I can go ahead and close this then for now. I will hold off submitting my app to the curated list until Flatpak support is added.

**Comment by danrabbit** [comment]
I'm going to reopen this issue because we will need Flatpak docs at some point and it's good to track it
