### ISSUE TITLE
submission-process.md still says "Loki 0.4.1" (line 47)

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/docs#6]
https://github.com/elementary/docs/blob/master/appcenter/submission-process.md#available-on-appcenter

First impulse, change it to something like:
"When your app passes automated testing and human review, it will become available in AppCenter in elementary OS."

**Comment by lewisgoddard** [comment]
I believe there is a build process for targeting multiple releases, which should probably be documented here.

**Comment by 4jNsY6fCVqZv** [comment]
How could such a documentation look like?
