### ISSUE TITLE
State we prefer Grid for Layout?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/docs#61]
Currently the [Getting Started](https://elementary.io/docs/code/getting-started#creating-layouts) only covers `Gtk.Grid`. 
But we don't explicitly state that we prefer using `Gtk.Grid` over for example `Gtk.Box`. While, I [understand](https://github.com/elementary/wingpanel-indicator-datetime/pull/99#issuecomment-435439794) from @jeremypw that we do.
Should we add this to the [reference](https://elementary.io/docs/code/reference) maybe?

**Comment by tintou** [comment]
I'm unsure that this is true anymore, GTK [used to imply in its documentation that GtkBox was going to be deprecated](https://developer.gnome.org/gtk3/3.8/gtk-migrating-GtkGrid.html), that's in fact not the case anymore. So we can use Gtk.Box if we want to.

**Comment by danrabbit** [comment]
Yeah it sounds like now they're keeping box to replace toolbar. So I guess this isn't relevant
