### ISSUE TITLE
Add Flatpak Sdk instuctions to Basic Setup

### ISSUE THREAD

**Issue by cassidyjames** [elementary/docs#73]
e.g. for those developing on elementary OS 5.

**Comment by jalcine** [comment]
Just ran into this from <https://docs.elementary.io/develop/writing-apps/our-first-app/packaging>. The SDK version is incorrect - would it be possible to link to the SDK's source / site itself so one could discern the proper version there?

**Comment by cassidyjames** [comment]
@jalcine thanks for pointing that out, but it's a separate issue. I've corrected the docs and added a note about it, but this issue is specifically for the Basic Setup section.

**Comment by jalcine** [comment]
Hm, that version doesn't work. Does it expect a particular remote?

**Comment by cassidyjames** [comment]
@jalcine I've updated the instructions in the Basic Setup section now

**Comment by jalcine** [comment]
Hm okay, I'm noticing this new line (to me):

> We’re going to assume that you’re working from a clean installation of elementary OS Juno Beta or later. 

I'm currently running Hera. I'm guessing these guides are mainly aligned for Beta users (I actually _just_ paid to be a supporter to get those builds and then saw that y'all announce them publicly - which made me more happy). Is it possible to embolden that bit of text?

**Comment by cassidyjames** [comment]
Ah that was actually old and outdated. I have updated it to reference 5.1 Hera which should still be applicable.
