### ISSUE TITLE
Provide users with test icons to use in the "Our first app" tutorial

### ISSUE THREAD

**Issue by colinkiama** [elementary/docs#78]
## Problem

Users currently have to go out of their way to create icons themselves. In order top complete the tutorial. 

This causes friction, causing a potential elementary developer to quit learning to make elementary apps. 

While you can continue the tutorial by removing paths to icons in the meson.build file, once you reach the "packaging" section, the Flatpak build will fail because icons are missing.

## Proposal

Provide users with test icons to download and add to their tutorial projects. This greatly increases the success rate of users who finish the tutorial  -> Higher chance of there being more elementary OS app developers

## Prior Art

The [Chrome Extensions tutorial](https://developer.chrome.com/docs/extensions/mv3/getstarted/#user_interface) provides a link to download a zip file filled with images, with instructions on how to add to the project.

![Screen Shot 2021-05-30 at 11 50 17](https://user-images.githubusercontent.com/16501024/120067528-0f474380-c074-11eb-920a-175857733d77.png)

**Comment by cassidyjames** [comment]
We could link to @micahilbery's icon template project, maybe?

**Comment by colinkiama** [comment]
Yeah, that could work! 😄 

As long as there are clear instructions on how to add icons from that repo to the project, it should be fine. 👍

**Comment by danrabbit** [comment]
Currently we kinda jam icons into `The Build System`. We should probably add a separate page after that section which covers making icons, using template icons, etc and adding them to the build system like we do with separating out the translations parts of the build system
