### ISSUE TITLE
Docs: Explain Granite

### ISSUE THREAD

**Issue by cassidyjames** [elementary/docs#9]
We mention that we're gonna teach devs how to use Granite at the beginning, but then we never actually do! :open_mouth: We should show how to use Granite for something like a Message Dialog, and cover adding the dependency to Meson and everything.

**Comment by danrabbit** [comment]
I think this is technically fixed since we have some stuff about Granite with launcher badges and progressbars. It would probably make sense to open individual new issues for specific parts of Granite to cover
